# Travis CI script

dist: bionic
sudo: required
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - python3
      - python3-pip
      - cmake-data
      - cmake

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python3 python3-setuptools
  - pyenv install 3.6.3
  - pyenv global 3.6.3
  #FSeam Python generator dependencies
  - sudo apt-get install python3-pip
  - sudo pip3 install ply conan
  - sudo pip3 install pip --upgrade
  - export PYTHONPATH=$PYTHONPATH:$(pwd):/usr/lib/python3/dist-packages:/usr/local/lib/python3.6/dist-packages
  - echo $PYTHONPATH
  - ls -la $(python-config --prefix)/
  - ls -la $(python-config --prefix)/bin/
  - ls -la $(python-config --prefix)/lib/
  - ls -la $(python-config --prefix)/include/python3.6m

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

before_script:
  - python3.6 -m venv myenv
  - cd ${TRAVIS_BUILD_DIR}

  # Use Debug builds for running Valgrind and building examples
  #  - cmake -H. -BBuild-Debug -DCMAKE_BUILD_TYPE=Debug -DTRAVIS_BUILD=ON
  # Don't bother with release build for coverage build
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DTRAVIS_BUILD=ON

script:
  - cd ${TRAVIS_BUILD_DIR}/build
  - make -j${nproc}
  - make test
  
